# Generated by Django 6.0.2 on 2026-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.URLField(default='https://newroad.com.tr/assets/img/logo-light.png')),
                ('logo_dark', models.URLField(default='https://newroad.com.tr/assets/img/logo-dark.png')),
                ('links', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Header Configuration',
            },
        ),
        migrations.CreateModel(
            name='HeroConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://newroad.com.tr/assets/video/hero.mp4')),
                ('poster_url', models.URLField(default='https://newroad.com.tr/assets/img/hero-poster.jpg')),
                ('title_line1', models.CharField(default='WE BUILD', max_length=100)),
                ('title_line2', models.CharField(default='DIGITAL PRODUCTS', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hero Configuration',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
