# Generated by Django 6.0.2 on 2026-02-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroconfiguration',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='heroconfiguration',
            name='video_url',
        ),
        migrations.AddField(
            model_name='heroconfiguration',
            name='poster_file',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='heroconfiguration',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
